# Generated by Django 5.1.5 on 2025-01-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f5_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('response_data', models.JSONField()),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='f5_devices.f5devicemodel')),
            ],
        ),
    ]
