# Generated by Django 5.1.5 on 2025-01-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f5_devices', '0002_healthcheckresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f5devicemodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='f5devicemodel',
            name='username',
        ),
        migrations.DeleteModel(
            name='HealthCheckResult',
        ),
    ]
