# Generated by Django 2.2 on 2020-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(verbose_name='Created at (UTC)')),
                ('stripe_charge_id', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
